[package]
name = "tesseract"
version = "0.1.0"
edition = "2024"
description = "A machine learning library written in Rust."

[dependencies]
csv = { version = "1.4.0", optional = true }
nalgebra = "0.34.1"
rand = { version = "0.9.2", optional = true }

[features]
default = ["io-csv", "rand"]
io-csv = ["dep:csv"]
rand = ["dep:rand"]
