[package]
name = "tesseract-core"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
nalgebra.workspace = true
serde = { workspace = true, optional = true}

[features]
default = []
serde = ["dep:serde"]
